name: arg-reform-inv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - pandas>=2.0.0
    - numpy>=1.24.0
    - requests>=2.31.0
    - duckdb>=0.9.0
    - python-dotenv>=1.0.0
    - plotly>=5.17.0
    - streamlit>=1.28.0
    - pytest>=7.4.0
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - schedule>=1.2.0
    - yfinance==0.2.44
    - sdmx1==2.22.0
    - pyyaml>=6.0.0
    - playwright>=1.40.0

